/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>
/* Header for class com_example_mathayus_myapplicationlearn_opncvNative */
using namespace std;
using namespace cv;
#ifndef _Included_com_example_mathayus_myapplicationlearn_opncvNative
#define _Included_com_example_mathayus_myapplicationlearn_opncvNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mathayus_myapplicationlearn_opncvNative
 * Method:    convertGray
 * Signature: (JJ)I
 */
 int detect(Mat& frame);

JNIEXPORT jint JNICALL Java_com_example_mathayus_myapplicationlearn_opncvNative_convertGray
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
